### ISSUE TITLE
Durandal NextGen Support?

### ISSUE THREAD

**Issue by gentledepp** [yagopv/DurandalAuth#21]
Hi!

I just read the blog post from rob eisenbert where he announces that Durandal is converging with AngularJS.

http://eisenbergeffect.bluespire.com/angular-and-durandal-converge/ 

He wrote a blog post about how to dev not so that migration later on is much easier:
http://eisenbergeffect.bluespire.com/preparing-for-durandal-nextgen/

Are these coding practives used in durandalauth? Sorry for this noob question but it is quite important for me to know that in order to make a proper decision. :/

**Comment by ajayjawale** [comment]
hey... that was in depth details... finally what is your thought after a year... with v2.0?
and if made public, can i get a look on AngularAuth?

regards,
Ajayj

**Comment by yagopv** [comment]
Hi,

Angular 2.0 is not ready for production at this time and its api is changing a lot between versions.

I have still in my mind the AngularAuth version of DurandalAuth but not having any timeline :(

Bye!!

**Comment by ajayjawale** [comment]
Hello Sir,

thanks for update...
i need one more favor from you!!!...-:)

I am pretty new to Durandal framework with the techs you used in
DurandalAuth project... and exploring the project to learn about the same...
I am stuck at one end, and i am sure that would be piece of cake for you...

problem is: i am trying to add a field on New and/or edit article modal
page... for that I did changed the Model & added following code in
dashboard.html

<div class="form-group" data-bind="validationElement: fullname">
                            <label class="control-label"
for="username">FullName</label>
                            <input class="form-control" type="text"
data-bind="value: fullname" placeholder="Full-Name">
</div>

then while debugging found that, i am getting fullname from database but on
application console m getting "_ReferenceError: fullname is not defined_"

now as per the study, i have to add the *fullname *in *dashboard.js
*as *ko.obserable...
*but unable to do so as I am stuck on finding from where & how the
binder,extenders, errrorvalidators are attached

Can you please help out here... what to do to get the db values in *fullname
field *in edit-article-view whereas insert into database in case of
new-article...

thank you,
regards,
AjaYJ

**Comment by yagopv** [comment]
Hi,

Did you remember to add the [DataMember] annotation in the new property??  It´s mandatory for BreezeJS entity mapping...

You have to add a new EntityFramework migration as well but I think you did it because you are saying the values are being retrieved from db ....

You can find some help in https://durandalauth.azurewebsites.net/home/help

Bye!!

**Comment by ajayjawale** [comment]
yes, i did added below in  Article-class in Domain-layer... and getting
appropriate data from DB... it look like problem with Client-Side
especially something with\* data-bind *where somewhere *fullname *is somehow
not getting bind with below defined datamember ...

```
    [Required]
    [StringLength(200)]
    [DataMember]
    public string FullName { get; set; }
```

tried debugging a lot & in js scripts even found appropriate db-values too
but no-luck in displaying same on page... any help would be highly
appreciated...

regards,
AjayJ

**Comment by yagopv** [comment]
Hi,

Your problem is _FullName_ is camelcased when translated to the JavaScript property. So you code should be:

```
<div class="form-group" data-bind="validationElement: fullName">
    <label class="control-label" for="fullName">Full name</label>
    <input class="form-control" type="text" data-bind="value: fullName" placeholder="Enter full name">
</div>
```

Note the uppercased "N" in full**N**ame

**Comment by ajayjawale** [comment]
oooopppsss  such a silly mistake...!!! :-)

really thanks man, got cleared now... what was the actual issue...

thanks a ton bro!!!
ajayj
