### ISSUE TITLE
IoC appears to be failing for MetadataController

### ISSUE THREAD

**Issue by jbeadles** [yagopv/DurandalAuth#28]
I have tried running the application straight from a pull as well as updating all dependencies and I am still met with a 500 error for /breeze/metadata.  Digging into it more it seems like IoC is causing the problem -- it is saying that MetadataController needs to have a paramaterless constructor.  I have been working with StructureMap recently and this is the exact error that I got when IoC was not configured correctly.

It seems like IoC is configured correctly, however -- perhaps I am missing something?  I tried adding in For\<IUnitOfWork\>().Use\<UnitOfWork\>(); but still am not having any luck.

**Comment by yagopv** [comment]
Hi,

Sorry for the late, late, late answer but I have no time lately :(

I just cloned the repo and execute it with no problem. 

Did you perhaps update the nuget packages ... ?? Because I did not change nothing in the last couple of months and perhaps some update is breaking the project ...

**Comment by iqbal369** [comment]
I am getting the same issue. 
The template works fine on Local Server. I get error when I deploy it to Production. (Hostgator windows server)
$id: "1"
$type: "System.Web.Http.HttpError, System.Web.Http"
Message: "An error has occurred."

**Comment by yagopv** [comment]
Hi,

I upgraded all nuget packages in the solution and updated as well the structuremap container to the most recent version. It implied some new code for the container so try again if you want and let me know

Bye!!

**Comment by iqbal369** [comment]
Thanks for reply but I already have fixed all the issues. Now it is working fine.

**Comment by yagopv** [comment]
Were the issues related to the project? 

If so, could you tell me how you solved to correct it in DurandalAuth?

Thanks!!
