### ISSUE TITLE
Does not run out of the box

### ISSUE THREAD

**Issue by neilyoung** [yagopv/DurandalAuth#29]
Complains about missing System.Web.Mvc.Ajax and System.Web.Mvc.Html

**Comment by iqbal369** [comment]
Hi Neilyoung!
I also experienced some issues like this. It was also not working after deployment. But I got all these fixed. Now it is working fine. Update your nuget packages  and it will be fixed.

**Comment by neilyoung** [comment]
Yes. Found it also already

**Comment by neilyoung** [comment]
Thanks BTW
