### ISSUE TITLE
IIS application only displays file directory instead of home page.

### ISSUE THREAD

**Issue by aqwright** [yagopv/DurandalAuth#30]
I've added the DurandalAuth solution as an application to IIS. I've tried everything but whenever I try to navigate to localhost/DurandalAuth, I only get the project file directory

**Comment by yagopv** [comment]
Hi,

Perhaps [this link](http://www.asp.net/mvc/overview/deployment/visual-studio-web-deployment/deploying-to-iis) could help you.

Check the steps and perhaps you can see the issue

Bye!!

**Comment by yagopv** [comment]
Hi,

I upgraded all nuget packages in the solution so if you are interested yet you can try again

Bye!!
