### ISSUE TITLE
Need to add more entities in LookupBundle

### ISSUE THREAD

**Issue by ItaSumit** [yagopv/DurandalAuth#32]
Hi,

I need to build master data for countries and cities. I am able to add both in Lookups method in DurandalAuthComtroller. But how to consume these in 'prepare' function in entitymanagerprovider.js  and afterwards in unitofwork.js.

Please help me on this.

Thanks.

**Comment by yagopv** [comment]
Hi,

1) Add the initialization in the unitofwork.js (In the same place as the another initializations)

```
this.countries= repository.create(provider, "Country", routeconfig.countriesUrl, breeze.FetchStrategy.FromLocalCache);
```

I´m  using the base repository class. If you need special methods you can override it like privatearticlesrepository or publicarticlesrepository does

2) In the entitymanagerprovider you don´t have to do nothing. It´s enough with adding the entities in the Controller (Lookups)

You can access the data using:

```
var categories = unitofwork.countries.all().then(function (countries) { });
```
