### ISSUE TITLE
IIS throwing 404 error: require.js not found

### ISSUE THREAD

**Issue by benitazz** [yagopv/DurandalAuth#35]
I have updated all packages and can run the app successfully on visual studio but when I publish the solution to IIS then the website is not loading, the website throws 404 exception.
I have checked the log files on IIS on the server and I can see that it complain about 2 things.
1. require.js not found
2. favicon.ico not not found - this is odd because nowhere in the project whereby the favicon is referenced, I do not understand this why it will throw this error.

I'm running IIS 8.5 on windows server 2012.
I can publish and run the other applications that I created by visual studio except the Durandal Auth application, please assist.

**Comment by yagopv** [comment]
Hi,

The first one seems to be a relative url configuration problem. Perhaps you can try to play with the

<base href="/">

in the <head> of the index.cshtml file

Did you build the project with weyland?

**Comment by benitazz** [comment]
Hi,

I'm building in visual studio 2013 and as I mentioned before when running the project on visual studio then everything is working.

only when I deployed to the server then I get 404 error.

**Comment by benitazz** [comment]
Hi,

I have built main-built.js using weyland, but to my surprise the out still contains you text. What I mean is that I changed the about page completely but when I check on the output I can see the following </i>    Who am I?</h1>\r\n                <p class="lead">My name is Yago and I am a developer who \r\n                is passionate about web design and programming.</p>     \r\n    

and my changes were added at the bottom, deleted and recreated the file using weyland and still getting the same results
